server:
  port: 8086
  servlet:
    context-path: "/ead-payment/"

spring:
  application:
    name: ead-payment-service

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
