server:
  port: 8084
  servlet:
    context-path: "/ead-notification/"

spring:
  application:
    name: ead-notification-service

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health
