server:
  port: 8084
  servlet:
    context-path: "/ead-notification/"

spring:
  application:
    name: ead-notification-service
  datasource:
    url: jdbc:postgresql://localhost:5433/ead-notification-v2
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show_sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
  output:
    ansi:
      enabled: always # Para visualizar cores no console utilizando Windows
  rabbitmq:
    addresses: amqps://wgrydoqs:VFGJQegZTobPz_5INWs9yM-WMv8sQhGf@beaver.rmq.cloudamqp.com/wgrydoqs

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notificationcommand
    queue:
      notificationCommandQueue:
        name: ead.notificationcommand.ms.notification
    key:
      notificationCommandKey: ms.notification
